ARG ros_distro=jazzy

FROM osrf/ros:${ros_distro}-desktop

ARG ros_distro
ENV ROS_DISTRO=${ros_distro}

# Copy scripts temporarily
COPY ../scripts/* /tmp/scripts/
RUN for file in /tmp/scripts/*.sh; do \
    chmod +x "$file"; \
    done

RUN apt-get update && apt-get install -y \
    git \
    clang \
    clangd-18 \
    clang-format-18 \
    clang-tidy-18 \
    sccache

# Install editorconfig-checker
RUN /tmp/scripts/install-ec.sh

RUN rm -rf /var/lib/apt/lists/*

RUN rm -rf /tmp/*

RUN echo "%ubuntu ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/ubuntu/.bashrc
